- hosts: local
  connection: local
  vars:
    region: eu-west-2
  vars_files:
    - aws_keys.yml
    - aws_vars.yml
    - generated_vars.yml
  tasks:
    - name: Gather EC2 facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Type": ["app","mySQL"]
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      register: ec2
    - debug: var=ec2

    - name: Terminate EC2 Instance(s)
      ec2:
        instance_ids: '{{ item.instance_id }}'
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      with_items: "{{ ec2.instances }}"

    - name: Remove lines from generated_vars and hosts file
      lineinfile:
        dest: "{{ item.dest }}"
        regexp: "{{ item.regexp }}"
        state: absent
      with_items:
        - {dest: '{{ hostpath }}', regexp: '^{{ APP_IP }}'}
        - {dest: '{{ hostpath }}', regexp: '^{{ DB_IP }}'}
        - {dest: './app.env', regexp: '^MYSQL_PORT_3306_TCP_ADDR='}
        - {dest: './generated_vars.yml', regexp: '^DB_IP:'}
        - {dest: './generated_vars.yml', regexp: '^WORKER_TOKEN:'}
        - {dest: './generated_vars.yml', regexp: '^APP_IP:'}
